--TABLES
-------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------
--COUNTRY ALL INDS
-------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS dopa_50.dopa_country_all_inds;
CREATE TABLE IF NOT EXISTS dopa_50.dopa_country_all_inds
(
    country_id bigint,
    country_name text,
    iso3 text,
    iso2 text,
    status text,
    country_tot_v_sqkm double precision,
    country_tot_sqkm double precision,
    country_prot_sqkm double precision,
    country_prot_perc_country_tot double precision,
    country_land_sqkm double precision,
    country_land_perc_country_tot double precision,
    country_land_prot_sqkm double precision,
    country_land_prot_perc_country_land double precision,
    country_marine_sqkm double precision,
    country_marine_perc_country_tot double precision,
    country_marine_prot_sqkm double precision,
    country_marine_prot_perc_country_marine double precision,
    protconn double precision,
    kba_n_tot bigint,
    kba_n_fully_prot bigint,
    kba_n_partially_prot bigint,
    kba_n_not_protected bigint,
    kba_avg_prot_perc_tot numeric,
    mta_perc_n_ecoregions_in_country text,
    pa_list integer[],
    pa_count integer,
    agb_min_c_mg_total double precision,
    agb_max_c_mg_total double precision,
    agb_mean_c_mg_total double precision,
    agb_tot_c_pg_total numeric,
    agb_min_c_mg_prot double precision,
    agb_max_c_mg_prot double precision,
    agb_mean_c_mg_prot double precision,
    agb_tot_c_pg_prot numeric,
    agb_min_c_mg_unprot double precision,
    agb_max_c_mg_unprot double precision,
    agb_mean_c_mg_unprot double precision,
    agb_tot_c_pg_unprot numeric,
    bgb_min_c_mg_total double precision,
    bgb_max_c_mg_total double precision,
    bgb_mean_c_mg_total double precision,
    bgb_tot_c_pg_total numeric,
    bgb_min_c_mg_prot double precision,
    bgb_max_c_mg_prot double precision,
    bgb_mean_c_mg_prot double precision,
    bgb_tot_c_pg_prot numeric,
    bgb_min_c_mg_unprot double precision,
    bgb_max_c_mg_unprot double precision,
    bgb_mean_c_mg_unprot double precision,
    bgb_tot_c_pg_unprot numeric,
    dwc_min_c_mg_total double precision,
    dwc_max_c_mg_total double precision,
    dwc_mean_c_mg_total double precision,
    dwc_tot_c_pg_total numeric,
    dwc_min_c_mg_prot double precision,
    dwc_max_c_mg_prot double precision,
    dwc_mean_c_mg_prot double precision,
    dwc_tot_c_pg_prot numeric,
    dwc_min_c_mg_unprot double precision,
    dwc_max_c_mg_unprot double precision,
    dwc_mean_c_mg_unprot double precision,
    dwc_tot_c_pg_unprot numeric,
    ltc_min_c_mg_total double precision,
    ltc_max_c_mg_total double precision,
    ltc_mean_c_mg_total double precision,
    ltc_tot_c_pg_total numeric,
    ltc_min_c_mg_prot double precision,
    ltc_max_c_mg_prot double precision,
    ltc_mean_c_mg_prot double precision,
    ltc_tot_c_pg_prot numeric,
    ltc_min_c_mg_unprot double precision,
    ltc_max_c_mg_unprot double precision,
    ltc_mean_c_mg_unprot double precision,
    ltc_tot_c_pg_unprot numeric,
    gsoc_min_c_mg_total double precision,
    gsoc_max_c_mg_total double precision,
    gsoc_mean_c_mg_total double precision,
    gsoc_tot_c_pg_total numeric,
    gsoc_min_c_mg_prot double precision,
    gsoc_max_c_mg_prot double precision,
    gsoc_mean_c_mg_prot double precision,
    gsoc_tot_c_pg_prot numeric,
    gsoc_min_c_mg_unprot double precision,
    gsoc_max_c_mg_unprot double precision,
    gsoc_mean_c_mg_unprot double precision,
    gsoc_tot_c_pg_unprot numeric,
    carbon_min_c_mg_total double precision,
    carbon_max_c_mg_total double precision,
    carbon_mean_c_mg_total double precision,
    carbon_tot_c_pg_total numeric,
    carbon_min_c_mg_prot double precision,
    carbon_max_c_mg_prot double precision,
    carbon_mean_c_mg_prot double precision,
    carbon_tot_c_pg_prot numeric,
    carbon_min_c_mg_unprot double precision,
    carbon_max_c_mg_unprot double precision,
    carbon_mean_c_mg_unprot double precision,
    carbon_tot_c_pg_unprot numeric,
    elev_min double precision,
    elev_max double precision,
    elev_mean double precision,
    gfc_gain_sqkm double precision,
    gfc_gain_prot_sqkm double precision,
    gfc_gain_perc_tot double precision,
    gfc_gain_prot_perc_tot double precision,
    gfc_loss_sqkm double precision,
    gfc_loss_prot_sqkm double precision,
    gfc_loss_perc_tot double precision,
    gfc_loss_prot_perc_tot double precision,
    gfc_treecover_land_sqkm double precision,
    gfc_treecover_land_perc_country_land double precision,
    gfc_treecover_land_prot_sqkm double precision,
    gfc_treecover_land_prot_perc_country_land double precision,
    gfc_treecover_land_prot_perc_country_land_prot double precision,
    gfc_treecover_land_prot_perc_gfc_treecover_land double precision,
    water_p_now_sqkm double precision,
    water_p_1985_sqkm double precision,
    water_p_netchange_sqkm double precision,
    water_p_netchange_perc_first_epoch double precision,
    water_p_prot_now_sqkm double precision,
    water_p_prot_1985_sqkm double precision,
    water_p_prot_netchange_sqkm double precision,
    water_p_prot_netchange_perc_first_epoch double precision,
    water_s_now_sqkm double precision,
    water_s_1985_sqkm double precision,
    water_s_netchange_sqkm double precision,
    water_s_netchange_perc_first_epoch double precision,
    water_s_prot_now_sqkm double precision,
    water_s_prot_1985_sqkm double precision,
    water_s_prot_netchange_sqkm double precision,
    water_s_prot_netchange_perc_first_epoch double precision,
    land_sqkm double precision,
    land_prot_sqkm double precision,
    lpd_null_sqkm double precision,
    lpd_null_perc_land_sqkm numeric,
    lpd_severe_sqkm double precision,
    lpd_severe_perc_land_sqkm numeric,
    lpd_moderate_sqkm double precision,
    lpd_moderate_perc_land_sqkm numeric,
    lpd_stable_stressed_sqkm double precision,
    lpd_stable_perc_land_sqkm numeric,
    lpd_stable_sqkm double precision,
    lpd_stable_stressed_perc_land_sqkm numeric,
    lpd_increased_sqkm double precision,
    lpd_increased_perc_land_sqkm numeric,
    lpd_prot_null_sqkm double precision,
    lpd_prot_null_perc_land_prot_sqkm numeric,
    lpd_prot_severe_sqkm double precision,
    lpd_prot_severe_perc_land_prot_sqkm numeric,
    lpd_prot_moderate_sqkm double precision,
    lpd_prot_moderate_perc_land_prot_sqkm numeric,
    lpd_prot_stable_stressed_sqkm double precision,
    lpd_prot_stable_perc_land_prot_sqkm numeric,
    lpd_prot_stable_sqkm double precision,
    lpd_prot_stable_stressed_perc_land_prot_sqkm numeric,
    lpd_prot_increased_sqkm double precision,
    lpd_prot_increased_perc_land_prot_sqkm numeric,
    mspa_core_1995_sqkm double precision,
    mspa_non_natural_1995_sqkm double precision,
    mspa_edge_1995_sqkm double precision,
    mspa_core_perforation_1995_sqkm double precision,
    mspa_islet_1995_sqkm double precision,
    mspa_linear_1995_sqkm double precision,
    mspa_core_2000_sqkm double precision,
    mspa_non_natural_2000_sqkm double precision,
    mspa_edge_2000_sqkm double precision,
    mspa_core_perforation_2000_sqkm double precision,
    mspa_islet_2000_sqkm double precision,
    mspa_linear_2000_sqkm double precision,
    mspa_core_2005_sqkm double precision,
    mspa_non_natural_2005_sqkm double precision,
    mspa_edge_2005_sqkm double precision,
    mspa_core_perforation_2005_sqkm double precision,
    mspa_islet_2005_sqkm double precision,
    mspa_linear_2005_sqkm double precision,
    mspa_core_2010_sqkm double precision,
    mspa_non_natural_2010_sqkm double precision,
    mspa_edge_2010_sqkm double precision,
    mspa_core_perforation_2010_sqkm double precision,
    mspa_islet_2010_sqkm double precision,
    mspa_linear_2010_sqkm double precision,
    mspa_core_2015_sqkm double precision,
    mspa_non_natural_2015_sqkm double precision,
    mspa_edge_2015_sqkm double precision,
    mspa_core_perforation_2015_sqkm double precision,
    mspa_islet_2015_sqkm double precision,
    mspa_linear_2015_sqkm double precision,
    lcc_esa_country_land_sqkm double precision,
    lcc_esa_country_land_prot_sqkm double precision,
    lcc_esa_lc1_1995 integer[],
    lcc_esa_lc1_2020 integer[],
    lcc_esa_land_sqkm double precision[],
    lcc_esa_land_prot_sqkm double precision[],
    lc_copernicus_code integer[],
    lc_copernicus_tot_sqkm double precision[],
    lc_copernicus_prot_sqkm double precision[],
    lc_copernicus_land_sqkm double precision[],
    lc_copernicus_land_prot_sqkm double precision[],
    lc_copernicus_marine_sqkm double precision[],
    lc_copernicus_marine_prot_sqkm double precision[],
    lc_copernicus_land_natural_sqkm double precision,
    lc_copernicus_land_natural_prot_sqkm double precision,
    lc_copernicus_land_forest_sqkm double precision,
    lc_copernicus_land_forest_prot_sqkm double precision,
    lc_copernicus_land_water_sqkm double precision,
    lc_copernicus_land_water_prot_sqkm double precision
);
REVOKE ALL ON TABLE dopa_50.dopa_country_all_inds FROM h05ibexro;
GRANT ALL ON TABLE dopa_50.dopa_country_all_inds TO h05ibex;
GRANT SELECT ON TABLE dopa_50.dopa_country_all_inds TO h05ibexro;
-------------------------------------------------------------------------------------------
--WDPA ALL INDS
-------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS dopa_50.dopa_wdpa_all_inds;
CREATE TABLE IF NOT EXISTS dopa_50.dopa_wdpa_all_inds
(
    wdpaid integer,
    pa_name text,
    desig_eng text,
    iucn_cat text,
    marine integer,
    is_n2k boolean,
    iso3 text,
    type text,
    area_geo double precision,
    pa_rtot_sqkm double precision,
    agb_min_c_mg double precision,
    agb_max_c_mg double precision,
    agb_mean_c_mg double precision,
    agb_tot_c_mg numeric,
    bgb_min_c_mg double precision,
    bgb_max_c_mg double precision,
    bgb_mean_c_mg double precision,
    bgb_tot_c_mg numeric,
    dwc_min_c_mg double precision,
    dwc_max_c_mg double precision,
    dwc_mean_c_mg double precision,
    dwc_tot_c_mg numeric,
    ltc_min_c_mg double precision,
    ltc_max_c_mg double precision,
    ltc_mean_c_mg double precision,
    ltc_tot_c_mg numeric,
    gsoc_min_c_mg double precision,
    gsoc_max_c_mg double precision,
    gsoc_mean_c_mg double precision,
    gsoc_tot_c_mg numeric,
    carbon_min_c_mg double precision,
    carbon_max_c_mg double precision,
    carbon_mean_c_mg double precision,
    carbon_tot_c_mg numeric,
    cli_tmax_01 double precision,
    cli_tmax_02 double precision,
    cli_tmax_03 double precision,
    cli_tmax_04 double precision,
    cli_tmax_05 double precision,
    cli_tmax_06 double precision,
    cli_tmax_07 double precision,
    cli_tmax_08 double precision,
    cli_tmax_09 double precision,
    cli_tmax_10 double precision,
    cli_tmax_11 double precision,
    cli_tmax_12 double precision,
    cli_tmean_01 double precision,
    cli_tmean_02 double precision,
    cli_tmean_03 double precision,
    cli_tmean_04 double precision,
    cli_tmean_05 double precision,
    cli_tmean_06 double precision,
    cli_tmean_07 double precision,
    cli_tmean_08 double precision,
    cli_tmean_09 double precision,
    cli_tmean_10 double precision,
    cli_tmean_11 double precision,
    cli_tmean_12 double precision,
    cli_tmin_01 double precision,
    cli_tmin_02 double precision,
    cli_tmin_03 double precision,
    cli_tmin_04 double precision,
    cli_tmin_05 double precision,
    cli_tmin_06 double precision,
    cli_tmin_07 double precision,
    cli_tmin_08 double precision,
    cli_tmin_09 double precision,
    cli_tmin_10 double precision,
    cli_tmin_11 double precision,
    cli_tmin_12 double precision,
    cli_prec_01 double precision,
    cli_prec_02 double precision,
    cli_prec_03 double precision,
    cli_prec_04 double precision,
    cli_prec_05 double precision,
    cli_prec_06 double precision,
    cli_prec_07 double precision,
    cli_prec_08 double precision,
    cli_prec_09 double precision,
    cli_prec_10 double precision,
    cli_prec_11 double precision,
    cli_prec_12 double precision,
    elev_min double precision,
    elev_max double precision,
    elev_mean double precision,
    gfc_gain_sqkm double precision,
    gfc_gain_perc_tot double precision,
    gfc_loss_sqkm double precision,
    gfc_loss_perc_tot double precision,
    gfc_treecover_land_sqkm double precision,
    gfc_treecover_land_perc_pa_land double precision,
    hdi_freq bigint,
    hdi_awhd double precision,
    mhdi numeric,
    water_p_now_sqkm double precision,
    water_p_1985_sqkm double precision,
    water_p_netchange_sqkm double precision,
    water_p_netchange_perc_first_epoch double precision,
    water_s_now_sqkm double precision,
    water_s_1985_sqkm double precision,
    water_s_netchange_sqkm double precision,
    water_s_netchange_perc_first_epoch double precision,
    lpd_null_sqkm double precision,
    lpd_null_perc_tot_sqkm numeric,
    lpd_severe_sqkm double precision,
    lpd_severe_perc_tot_sqkm numeric,
    lpd_moderate_sqkm double precision,
    lpd_moderate_perc_tot_sqkm numeric,
    lpd_stable_stressed_sqkm double precision,
    lpd_stable_perc_tot_sqkm numeric,
    lpd_stable_sqkm double precision,
    lpd_stable_stressed_perc_tot_sqkm numeric,
    lpd_increased_sqkm double precision,
    lpd_increased_perc_tot_sqkm numeric,
    mspa_core_1995_sqkm double precision,
    mspa_non_natural_1995_sqkm double precision,
    mspa_edge_1995_sqkm double precision,
    mspa_core_perforation_1995_sqkm double precision,
    mspa_islet_1995_sqkm double precision,
    mspa_linear_1995_sqkm double precision,
    mspa_core_2000_sqkm double precision,
    mspa_non_natural_2000_sqkm double precision,
    mspa_edge_2000_sqkm double precision,
    mspa_core_perforation_2000_sqkm double precision,
    mspa_islet_2000_sqkm double precision,
    mspa_linear_2000_sqkm double precision,
    mspa_core_2005_sqkm double precision,
    mspa_non_natural_2005_sqkm double precision,
    mspa_edge_2005_sqkm double precision,
    mspa_core_perforation_2005_sqkm double precision,
    mspa_islet_2005_sqkm double precision,
    mspa_linear_2005_sqkm double precision,
    mspa_core_2010_sqkm double precision,
    mspa_non_natural_2010_sqkm double precision,
    mspa_edge_2010_sqkm double precision,
    mspa_core_perforation_2010_sqkm double precision,
    mspa_islet_2010_sqkm double precision,
    mspa_linear_2010_sqkm double precision,
    mspa_core_2015_sqkm double precision,
    mspa_non_natural_2015_sqkm double precision,
    mspa_edge_2015_sqkm double precision,
    mspa_core_perforation_2015_sqkm double precision,
    mspa_islet_2015_sqkm double precision,
    mspa_linear_2015_sqkm double precision,
    p_agriculture_pa_perc_tot double precision,
    p_builtup_pa_sqkm numeric,
    p_builtup_pa_perc_land double precision,
    p_population_pa_last_epoch_sum numeric,
    p_population_pa_last_epoch_density numeric,
    p_population_pa_density_change numeric,
    p_population_pa_change_perc_first_epoch numeric,
    p_road_pa_perc_tot numeric,
    lc_esa_code integer[],
    lc_esa_1995_sqkm double precision[],
    lc_esa_2000_sqkm double precision[],
    lc_esa_2005_sqkm double precision[],
    lc_esa_2010_sqkm double precision[],
    lc_esa_2015_sqkm double precision[],
    lc_esa_2020_sqkm double precision[],
    lcc_esa_pa_tot_sqkm double precision,
    lcc_esa_lc1_1995 integer[],
    lcc_esa_lc1_2020 integer[],
    lcc_esa_sqkm double precision[],
    lc_copernicus_code integer[],
    lc_copernicus_tot_sqkm double precision[]
);
REVOKE ALL ON TABLE dopa_50.dopa_wdpa_all_inds FROM h05ibexro;
GRANT ALL ON TABLE dopa_50.dopa_wdpa_all_inds TO h05ibex;
GRANT SELECT ON TABLE dopa_50.dopa_wdpa_all_inds TO h05ibexro;
